
spring:
  datasource:
    # mysql????
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33062/db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8888
  servlet:
    context-path: /springApi